name: NISMOD v2.0.0
# ------------------------------------------------
scenario_sets:
- name: adoption
  description: Adoption curves for FTTP
  facets:
  - name: adoption
    description: ''
region_definitions:
# shared understanding of regions within the modelled area (e.g. GB)
- description: Broadband network distributions (Fixed network)
  filename: ../digital_comms/processed/assets_layer4_distributions.shp
  name: broadband_distributions
- description: Broadband network cabinets (Fixed network)
  filename: ../digital_comms/processed/assets_layer3_cabinets.shp
  name: broadband_cabinets
- description: Boundary of Great Britain
  filename: national.shp
  name: national
- description: Local Authority Districts
  filename: lad_uk_2016-12/lad_uk_2016-12.shp
  name: lad2016
# ------------------------------------------------
interval_definitions:
# shared understanding of time intervals within a year
- description: One annual interval of 8760 hours
  filename: annual_intervals.csv
  name: annual
# ------------------------------------------------
units: units.txt
# ------------------------------------------------
scenarios:
- name: fttp_baseline_adoption
  description: Baseline FTTP adoption for the UK
  scenario_set: adoption
  facets:
  - name: adoption
    filename: fttp_baseline_adoption.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: meters
- name: fttp_high_adoption
  description: High FTTP adoption for the UK
  scenario_set: adoption
  facets:
  - name: adoption
    filename: fttp_high_adoption.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: meters
- name: fttp_low_adoption
  description: Low FTTP adoption for the UK
  scenario_set: adoption
  facets:
  - name: adoption
    filename: fttp_low_adoption.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: meters
- name: fttdp_baseline_adoption
  description: Baseline FTTDP adoption for the UK
  scenario_set: adoption
  facets:
  - name: adoption
    filename: fttdp_baseline_adoption.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: meters
- name: fttdp_high_adoption
  description: High FTTDP adoption for the UK
  scenario_set: adoption
  facets:
  - name: adoption
    filename: fttdp_high_adoption.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: meters
- name: fttdp_low_adoption
  description: Low FTTDP adoption for the UK
  scenario_set: adoption
  facets:
  - name: adoption
    filename: fttdp_low_adoption.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: meters
narrative_sets:
- description: Picks a technology to roll out
  name: technology
narratives:
- name: fttp_rollout_per_distribution
  description: ''
  filename: fttp_rollout_per_distribution.yml
  narrative_set: technology_strategy
- name: fttp_subsidised_rollout_per_distribution
  description: ''
  filename: fttp_subsidised_rollout_per_distribution.yml
  narrative_set: technology_strategy
- name: fttdp_rollout_per_distribution
  description: ''
  filename: fttdp_rollout_per_distribution.yml
  narrative_set: technology_strategy
- name: fttdp_subsidised_rollout_per_distribution
  description: ''
  filename: fttdp_subsidised_rollout_per_distribution.yml
  narrative_set: technology_strategy
