name: NISMOD v2.0.0
# ------------------------------------------------
scenario_sets:
- name: adoption
  description: Adoption curves for FTTP
  facets:
  - name: adoption
    description: ''
region_definitions:
# shared understanding of regions within the modelled area (e.g. GB)
- description: Broadband network distributions (Fixed network)
  filename: ../digital_comms/processed/assets_layer4_distributions.shp
  name: broadband_distributions
- description: Broadband network cabinets (Fixed network)
  filename: ../digital_comms/processed/assets_layer3_cabinets.shp
  name: broadband_cabinets
- description: Boundary of Great Britain
  filename: national.shp
  name: national
# ------------------------------------------------
interval_definitions:
# shared understanding of time intervals within a year
- description: One annual interval of 8760 hours
  filename: annual_intervals.csv
  name: annual
# ------------------------------------------------
units: units.txt
# ------------------------------------------------
scenarios:
- name: baseline_adoption
  description: Baseline FTTP adoption for the UK
  scenario_set: adoption
  facets:
  - name: adoption
    filename: baseline_adoption.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: meters
- name: high_adoption
  description: High FTTP adoption for the UK
  scenario_set: adoption
  facets:
  - name: adoption
    filename: high_adoption.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: meters
- name: low_adoption
  description: Low FTTP adoption for the UK
  scenario_set: adoption
  facets:
  - name: adoption
    filename: low_adoption.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: meters
narrative_sets: []
narratives: []
