name: NISMOD v2.0.0
# ------------------------------------------------
scenario_sets:
- name: adoption
  description: Adoption curves 
  facets:
  - name: adoption
    description: ''
region_definitions:
# shared understanding of regions within the modelled area (e.g. GB)
- description: Broadband network distributions (Fixed network)
  filename: ../digital_comms/processed/assets_layer4_distributions.shp
  name: broadband_distributions
- description: Boundary of Great Britain
  filename: national.shp
  name: national
- description: Local Authority Districts
  filename: lad_uk_2016-12/lad_uk_2016-12.shp
  name: lad2016
# ------------------------------------------------
interval_definitions:
# shared understanding of time intervals within a year
- description: One annual interval of 8760 hours
  filename: annual_intervals.csv
  name: annual
# ------------------------------------------------
units: units.txt
# ------------------------------------------------
scenarios:
- name: low_adoption
  description: Low adoption 
  scenario_set: adoption
  facets:
  - name: low_adoption
    filename: low_adoption.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: meters
- name: baseline_adoption
  description: Baseline adoption
  scenario_set: adoption
  facets:
  - name: baseline_adoption
    filename: baseline_adoption.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: meters
- name: high_adoption
  description: High adoption
  scenario_set: adoption
  facets:
  - name: high_adoption
    filename: high_adoption.csv
    spatial_resolution: national
    temporal_resolution: annual
    units: meters
narrative_sets:
- description: Picks a technology to roll out
  name: technology
narratives:
- name: fttp_s1_market_based_roll_out
  description: ''
  filename: fttp_s1.yml
  narrative_set: technology_strategy
- name: fttp_s2_rural_based_subsidy
  description: ''
  filename: fttp_s2.yml
  narrative_set: technology_strategy
- name: fttp_s3_outside_in_subsidy
  description: ''
  filename: fttp_s3.yml
  narrative_set: technology_strategy
- name: fttdp_s1_market_based_roll_out
  description: ''
  filename: fttp_s1.yml
  narrative_set: technology_strategy
- name: fttdp_s2_rural_based_subsidy
  description: ''
  filename: fttp_s2.yml
  narrative_set: technology_strategy
- name: fttdp_s3_outside_in_subsidy
  description: ''
  filename: fttp_s3.yml
  narrative_set: technology_strategy
