convergence_absolute_tolerance: 1e-05
convergence_relative_tolerance: 1e-05
dependencies: []
description: Test model for digital_comms
max_iterations: 1
name: digital_comms_only
narrative_sets: []
scenario_sets: []
sector_models:
- digital_comms
