decision_module: ''
description: ''
name: digital_comms_test
narratives: {}
scenarios: {}
strategies: []
sos_model: digital_comms_only
stamp: '2018-05-01T12:36:34.374Z'
timesteps:
- 2015
- 2020
- 2025
